name: caller-repo
on:
  #repository_dispatch:
   # types: [trigger-workflow]
  workflow_dispatch:


jobs:
  remote:
    runs-on: ubuntu-latest
    steps:
      - name: hello
        run: echo hello world
      - name: Trigger Workflow
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{secrets.ACCESS_TOKEN}}
          repository: goyal20nikita/cross-repo-triggering-2
          event-type: trigger-workflow
